apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: bitwarden-secretsmanager
spec:
  provider:
    bitwardensecretsmanager:
      auth:
        secretRef:
          credentials:
            key: token
            name: bitwarden-access-token
            namespace: external-secrets
      bitwardenServerSDKURL: https://bitwarden-sdk-server.external-secrets.svc.cluster.zhenkai.dev.local:9998
      caProvider:
        secretRef:
          name: bitwarden-tls-bundle
          key: root-certs.pem
      organizationID: 35dbf8ba-d7ec-4f9f-be4d-b0b3001e9375
      projectID: 429c0a08-0e15-44ac-9277-b3ac00299773
