---
apiVersion: v1
kind: Namespace
metadata:
  name: csi-rclone
  labels:
    toolkit.fluxcd.io/tenant: infra
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: csi-rclone
  namespace: csi-rclone
spec:
  type: oci
  interval: 24h
  url: oci://ghcr.io/veloxpack/charts/csi-driver-rclone
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-rclone
  namespace: csi-rclone
spec:
  interval: 12h
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 3m
  chart:
    spec:
      chart: csi-rclone
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: csi-rclone
        namespace: csi-rclone
      interval: 12h
