apiVersion: v1
kind: Namespace
metadata:
  name: kyverno
  labels:
    toolkit.fluxcd.io/tenant: infra
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kyverno
  namespace: kyverno
spec:
  interval: 24h
  url: https://kyverno.github.io/kyverno/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
spec:
  interval: 12h
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 3m
  chart:
    spec:
      chart: kyverno
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: kyverno
      interval: 12h
