---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: trust-manager
  namespace: cert-manager
spec:
  type: oci
  interval: 24h
  url: oci://quay.io/jetstack/charts/trust-manager
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trust-manager
  namespace: cert-manager
spec:
  interval: 12h
  dependsOn:
    - name: cert-manager
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 3m
  chart:
    spec:
      chart: trust-manager
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: trust-manager
        namespace: cert-manager
      interval: 12h
