apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: bitwarden-bootstrap-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bitwarden-bootstrap-certificate
  namespace: cert-manager
spec:
  # this is discouraged but required by ios
  commonName: cert-manager-bitwarden-tls
  isCA: true
  secretName: bitwarden-bootstrap-tls-certs
  subject:
    organizations:
      - external-secrets.io
  dnsNames:
    - external-secrets-bitwarden-sdk-server.default.svc.cluster.zhenkai.dev.local
    - bitwarden-sdk-server.default.svc.cluster.zhenkai.dev.local
    - localhost
  ipAddresses:
    - 127.0.0.1
    - ::1
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  issuerRef:
    name: bitwarden-bootstrap-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: bitwarden-certificate-issuer
spec:
  ca:
    secretName: bitwarden-bootstrap-tls-certs
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bitwarden-tls-certs
  namespace: cert-manager
spec:
  secretName: bitwarden-tls-certs
  dnsNames:
    - external-secrets-bitwarden-sdk-server.default.svc.cluster.zhenkai.dev.local
    - bitwarden-sdk-server.default.svc.cluster.zhenkai.dev.local
    - localhost
  ipAddresses:
    - 127.0.0.1
    - ::1
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  issuerRef:
    name: bitwarden-certificate-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: bitwarden-tls-bundle # The bundle name will also be used for the target
spec:
  sources:
    - useDefaultCAs: true
    - secret:
        name: "bitwarden-tls-certs"
        key: "ca.crt"
  target:
    configMap:
      key: "root-certs.pem"
      metadata:
        labels:
          app.kubernetes.io/component: "trust-bundle"
    namespaceSelector:
      matchLabels:
        bundle: bitwarden
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: sync-bitwarden-cert
  annotations:
    policies.kyverno.io/title: Sync Bitwarden Cert
    policies.kyverno.io/subject: Secret
    policies.kyverno.io/description: >-
      Synchronizes the bitwarden-tls-certs secret from the cert-manager 
      namespace to the external-secrets namespace.
spec:
  rules:
    - name: sync-secret-to-external-secrets
      match:
        any:
          - resources:
              kinds:
                - Secret
              names:
                - bitwarden-tls-certs
              namespaces:
                - cert-manager
      generate:
        apiVersion: v1
        kind: Secret
        name: bitwarden-tls-certs
        namespace: external-secrets
        synchronize: true
        clone:
          namespace: cert-manager
          name: bitwarden-tls-certs
  values:
    backgroundController:
      rbac:
        clusterRole:
          extraResources:
            - apiGroups:
                - ""
              resources:
                - secrets
              resourceNames:
                - "bitwarden-tls-certs"
              verbs:
                - get
                - list
                - watch
                - create
                - update
                - delete
